Task11, Group10, Стрельцова Александрина
yeputons/spring-2019-paradigms-tasks pull request #218
Opened 2019-05-17 19:43 UTC by aleksandrina-streltsova

2019-05-17 22:40 UTC, edgarzhavoronkov requested changes
Добрый вечер, автотесты проходят, по коду есть несколько ремарок

2019-05-17 22:40 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    fromList = foldl (\t (k, v) -> insert k v t) empty
Тут можно воспользоваться либо правой сверткой(`foldr`), либо оставить левую, но задействовать (`uncurry` и `flip`) что бы от лямбды избавиться

2019-05-17 22:40 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    insertWith f k v = alter (\case
Посмотрите в сторону `maybe`, она ровно этим и занимается

2019-05-17 22:40 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    delete = alter (const Nothing)
Вместо таких скобок можно `$` использовать

2019-05-17 22:40 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    adjust f = alter (fmap f)
Аналогично про `$`

2019-05-17 22:40 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    member k t = isJust (Map.lookup k t)
Для красоты можно композицией воспользоваться, как и далее

2019-05-17 22:40 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    null t = (size t == 0)
Внешние скобки не нужны

2019-05-17 22:40 UTC, edgarzhavoronkov commented on task11/src/NaiveTree.hs
> +    toAscList (Node k a l r) = toAscList l ++ ((k, a):toAscList r)
Пробелы вокруг `:`

2019-05-17 22:40 UTC, edgarzhavoronkov commented on task11/test/TestMap.hs
> +        testGroup "Test memeber" [
```suggestion
        testGroup "Test member" [
```

2019-05-17 22:40 UTC, edgarzhavoronkov commented on task11/test/TestMap.hs
> +        testGroup "Test notMemeber" [
```suggestion
        testGroup "Test notMember" [
```

2019-05-18 09:39 UTC, aleksandrina-streltsova commented
@edgarzhavoronkov, исправлено

2019-05-18 12:14 UTC, yeputons requested changes
До корректности остались тесты (как минимум для `updateWithKey`, `alter`, `size`)

2019-05-18 12:14 UTC, yeputons commented on task11/src/Map.hs
> +
Изменение не по делу

2019-05-18 12:14 UTC, yeputons commented on task11/src/NaiveTree.hs
> +merge (Node k a ll lr) r = Node k a ll (merge lr r)
Выравнивайте аргументы функции друг под другом

2019-05-18 12:14 UTC, yeputons commented on task11/src/NaiveTree.hs
> +    toAscList (Node k a l r) = toAscList l ++ ((k, a) : toAscList r)
Выравнивайте `=` друг под другом.
Внешние скобки справа не нужны

2019-05-18 12:14 UTC, yeputons commented on task11/src/NaiveTree.hs
> +                a' = maybe Nil (singleton k) (f (Just a)) in
Тут лучше `empty` вместо `Nil` для симметрии. А ещё это очень похоже на первый случай, можно вынести в общую функцию в `where`.

2019-05-18 12:14 UTC, yeputons commented on task11/src/NaiveTree.hs
> +    lookup k' (Node k a l r)
Выравнивайте аргументы друг под другом

2019-05-18 12:14 UTC, yeputons commented on task11/src/NaiveTree.hs
> +    alter f k' (Node k a l r)
Выравнивайте аргументы друг под другом

2019-05-18 12:14 UTC, yeputons commented on task11/src/NaiveTree.hs
> +    null _ = False
Выравнивайте `=`

2019-05-18 12:14 UTC, yeputons commented on task11/src/NaiveTree.hs
> +    size (Node _ _ l r) = 1 + size l + size r
Выравнивайте `=`

2019-05-18 12:14 UTC, yeputons commented on task11/test/TestMap.hs
> +        testGroup "Test insert" [
Слово `Test` лишнее, можно просто `insert`. И так понятно, что это тест. Аналогично везде ниже

2019-05-18 12:14 UTC, yeputons commented on task11/test/TestMap.hs
> +            testCase "insert in empty map" $
Слово `insert` лишнее, это следует из названия группы. Можно просто `to empty map`. Аналогично везде ниже.

2019-05-18 16:17 UTC, aleksandrina-streltsova commented
@yeputons, исправлено

2019-05-18 17:15 UTC, yeputons requested changes
Корректность есть, по стилю почти успех.

2019-05-18 17:15 UTC, yeputons commented on task11/test/TestMap.hs
> +            testCase "existent key" $
Лучше `existing`, ниже аналогично и аналогично с `non-existing` (см. [тут](https://ell.stackexchange.com/a/16167)).

2019-05-18 17:15 UTC, yeputons commented on task11/src/NaiveTree.hs
> +        where g = maybe empty (singleton k')
`f` не используется нигде, кроме `g`, сюда лучше и ввести.
И дальше переименовать `g` во что-нибудь вроде `insertedAt`

2019-05-18 17:15 UTC, yeputons commented on task11/src/NaiveTree.hs
> +        case t of
Как-то я не подумал, что `where` бывает только у одного объявления. В целом `case` на верхнем уровне вместо pattern matching — это не очень хорошо, ну да ладно, добьём тут. Прошу прощения.

С этим комментарием ничего делать не надо.

2019-05-18 17:38 UTC, aleksandrina-streltsova commented
@yeputons, исправлено

2019-05-18 18:21 UTC, yeputons approved these changes
Успех!

2019-05-18 18:21 UTC, closed without merging