Task11, Group09, Быков Никита
yeputons/spring-2019-paradigms-tasks pull request #225
Opened 2019-05-17 23:33 UTC by StillBlueSkyOverhead

2019-05-18 08:17 UTC, yeputons requested changes
У вас слишком большие изменения файлов (см. вкладку `Files changed`). Кажется, что-то не так с отступами, поэтому получается, что изменились примерно все строчки.

А так автотесты проходят

2019-05-18 17:43 UTC, StillBlueSkyOverhead commented
@yeputons, исправлено

2019-05-18 18:28 UTC, yeputons requested changes
Корректность есть

2019-05-18 18:28 UTC, yeputons commented on task11/src/Map.hs
> +    fromList = foldl (flip (uncurry insert)) empty
Внутренние скобочки лучше заменить на `$`

2019-05-18 18:28 UTC, yeputons commented on task11/src/Map.hs
> +    update f = alter (maybe Nothing f)
Тут лучше `$`

2019-05-18 18:28 UTC, yeputons commented on task11/src/Map.hs
> +    null = (0 == ) . size
Лучше `== 0`

2019-05-18 18:28 UTC, yeputons commented on task11/src/NaiveTree.hs
> +merge (Node k a l r) r' = Node k a l (merge r r')
Выравнивайте аргументы друг под другом

2019-05-18 18:28 UTC, yeputons commented on task11/src/NaiveTree.hs
> +    singleton k a = Node k a Nil Nil
Неконсистентно: у вас иногда значение называется `v` (например, в `Map.hs`). Выберите что-то одно.

2019-05-18 18:28 UTC, yeputons commented on task11/src/NaiveTree.hs
> +            in merge l r'
`r'` не нужен

2019-05-18 18:28 UTC, yeputons commented on task11/src/NaiveTree.hs
> +            r' = maybe r (\a' -> merge (singleton k a') r) (f (Just a))
Тут можно немного упростить, если всегда мёржить, но иногда не с синглтоном, а с пустым мэпом.

2019-05-18 18:28 UTC, yeputons commented on task11/test/TestMap.hs
> +                let map = singleton "yeputons" "reads this" :: m String String in
True though

2019-05-18 19:42 UTC, StillBlueSkyOverhead commented
@yeputons, исправлено

2019-05-18 19:58 UTC, yeputons requested changes

2019-05-18 19:58 UTC, yeputons commented on task11/src/NaiveTree.hs
> +        | otherwise = let
Пустой `let`

2019-05-18 19:58 UTC, yeputons commented on task11/src/NaiveTree.hs
> +            in merge l (maybe r (flip merge r . singleton k) (f (Just a)))
Внешние скобки стоит заменить на `$`, скобки после `f` — тоже.

2019-05-18 20:00 UTC, StillBlueSkyOverhead commented
@yeputons, исправлено

2019-05-19 20:56 UTC, yeputons approved these changes
Успех! Но, да, увы, после дедлайна :(

Впрочем, на зачёт у вас полные шансы без допзаданий: осталось набрать 2.75 баллов, а домашка по SQL даёт шесть.

2019-05-19 20:56 UTC, closed without merging