Task12, Group10, Стрельцова Александрина
yeputons/spring-2019-paradigms-tasks pull request #227
Opened 2019-05-18 08:32 UTC by aleksandrina-streltsova

2019-05-18 12:06 UTC, yeputons requested changes
* `01.sql`: ответ верный
* `02.sql`: не сошлось число столбцов: ожидалось 2, получено 1
* `03.sql`: ответ верный

2019-05-18 12:06 UTC, yeputons commented on task12/02.sql
> +WHERE Rate = (SELECT MAX(Rate) FROM LiteracyRate));
Тут выбирается максимальный уровень грамотности за все времена, а надо "по последним данным для страны"

2019-05-18 12:06 UTC, yeputons commented on task12/03.sql
> +WHERE Id = (SELECT CityId From Capital
Используйте `JOIN` вместо подзапросов.

2019-05-18 12:06 UTC, yeputons commented on task12/03.sql
> +Where Name = "Malaysia"));
`WHERE`

2019-05-20 19:14 UTC, edgarzhavoronkov commented
Так как у вас есть уже зачет, то я закрою этот реквест, если не возражаете

2019-05-20 19:14 UTC, closed without merging