Task11, Group09, Павлов Иван
yeputons/spring-2019-paradigms-tasks pull request #229
Opened 2019-05-18 09:50 UTC by pavlov200912

2019-05-18 10:59 UTC, yeputons requested changes
Для корректности не хватает:
* `notMember` выражается через `member`
* Тестов для `alter`, `lookup`

2019-05-18 10:59 UTC, yeputons commented on task11/src/Map.hs
> +    adjust f = alter (\case
Для этого `case` есть готовая функция высшего порядка

2019-05-18 10:59 UTC, yeputons commented on task11/src/Map.hs
> +    notMember k = isNothing . Map.lookup k
Эта функция должна быть выражена через `member`

2019-05-18 10:59 UTC, yeputons commented on task11/src/NaiveTree.hs
> +merge (Node k a ll lr) r = Node k a ll $ merge lr r
Выравнивайте аргументы функции друг под другом

2019-05-18 10:59 UTC, yeputons commented on task11/src/NaiveTree.hs
> +    alter f key Nil                        = maybe Nil (singleton key) (f Nothing)
Лучше `empty` вместо `Nil` для симметрии с `singleton`

2019-05-18 10:59 UTC, yeputons commented on task11/src/NaiveTree.hs
> +                               merge l $ merge (maybe Nil (singleton k) $ f (Just a)) r
Лайк, прикольная идея.

А ещё лучше `empty` вместо `Nil` для симметрии с `singleton`. И, возможно, лучше вынести тогда этот `maybe` в отдельную вспомогательную функцию в `where`

2019-05-18 10:59 UTC, yeputons commented on task11/src/NaiveTree.hs
> +    lookup key (Node k a l r) | key < k   = Map.lookup key l
Выравнивайте аргументы друг под другом (`Nil` и шаблон)

2019-05-18 10:59 UTC, yeputons commented on task11/test/TestMap.hs
> +
Изменение не по делу, ниже есть аналогичные

2019-05-18 10:59 UTC, yeputons commented on task11/test/TestMap.hs
> +        testGroup "insert tests" [
Просто `insert`, и так понятно, что это тесты. В остальных группах аналогично

2019-05-18 10:59 UTC, yeputons commented on task11/test/TestMap.hs
> +            testCase "insert in case value replaced" $
Просто `value replaced`, остальное следует из названия группы. Аналогично в остальных тестах.

2019-05-18 10:59 UTC, yeputons commented on task11/test/TestMap.hs
> +        let f key new_value old_value = (show key) ++ ":" ++ new_value ++ "|" ++ old_value in
Скобочки не нужны

2019-05-18 10:59 UTC, yeputons commented on task11/test/TestMap.hs
> +        let f key x = (show key) ++ ":new " ++ x in
Скобочки не нужны

2019-05-18 10:59 UTC, yeputons commented on task11/test/TestMap.hs
> +        let f k x = if x == "a" then Just ((show k) ++ ":new a") else Nothing in
Внутренние скобочки не нужны

2019-05-19 07:46 UTC, pavlov200912 commented
@yeputons-bot, исправлено

2019-05-19 21:08 UTC, yeputons requested changes
Корректность есть

2019-05-19 21:08 UTC, yeputons commented on task11/src/Map.hs
> +    notMember k m = not (member k m)
Лучше выразить как композицию функцию и избавиться от `m`

2019-05-19 21:08 UTC, yeputons commented on task11/src/NaiveTree.hs
> +                               | otherwise = let v = (maybe empty (singleton k) $ f (Just a)) in
Скобочки вокруг `maybe` не нужны

2019-05-19 21:08 UTC, yeputons commented on task11/test/TestMap.hs
> +        testGroup "lookup" [
Стоит писать тесты функций в том же порядке, в котором они объявлены в `Map.hs`

2019-05-19 21:08 UTC, yeputons commented on task11/test/TestMap.hs
> +            testCase "in case member" $
Просто `member` (или вроде грамматически более корректное `if member`), аналогично в остальных тестах

2019-05-19 21:08 UTC, yeputons commented on task11/test/TestMap.hs
> +                let val = Map.lookup 5 (fromList [(5,"a"), (3,"b")] :: m Int String) in
`let` не нужен, ниже в `insert` аналогично

2019-05-19 21:08 UTC, yeputons commented on task11/test/TestMap.hs
> +                Map.size map @?= 2,
Лучше все тесты на `delete` делать одинаковыми, т.е. проверять `notMember` или что-то такое. Или размер проверять сразу везде.

2019-05-22 18:45 UTC, closed without merging