Task12, Group09, Горбачев Егор
yeputons/spring-2019-paradigms-tasks pull request #230
Opened 2019-05-18 13:50 UTC by Peltorator

@yeputons, исправлено

2019-05-18 14:22 UTC, yeputons approved these changes
* `01.sql`: ответ верный

Зачёт, однако, поздравляю!

2019-05-18 15:04 UTC, Peltorator commented
> * `01.sql`: ответ верный
> 
> Зачёт, однако, поздравляю!

УРАААААА!!!

2019-05-19 13:24 UTC, Peltorator commented
@yeputons, исправлено

2019-05-19 21:02 UTC, yeputons requested changes
* `01.sql`: ответ верный
* `03.sql`: ответ верный
* `05.sql`: неправильный ответ
* `06.sql`: неправильный ответ, тут есть небольшой классический подвох
* `07.sql`: неправильный ответ, идея в общих чертах верная

2019-05-21 04:53 UTC, Peltorator commented
@yeputons, исправлено

2019-05-21 09:41 UTC, yeputons requested changes
* `01.sql`: ответ верный
* `02.sql`: ожидалась ровно одна точка с запятой, плюс. см. комментарий
* `03.sql`: ответ верный
* `04.sql`: не сошлось число строк: ожидалось 239, получено 77
* `05.sql`: ответ верный
* `06.sql`: ответ верный
* `07.sql`: всё ещё так же неправильный ответ. Подсказка: перечитайте задание

2019-05-21 09:41 UTC, yeputons commented on task12/02.sql
> +    SELECT MAX(LiteracyRate.Year), LiteracyRate.CountryCode, LiteracyRate.Rate FROM LiteracyRate
Непонятно, чему тут равно `LiteracyRate.Rate`: это и не поле группировки, и не агрегирующая функция.

2019-05-21 10:05 UTC, Peltorator commented on task12/02.sql
> +    SELECT MAX(LiteracyRate.Year), LiteracyRate.CountryCode, LiteracyRate.Rate FROM LiteracyRate
Я не понял(

2019-05-21 10:09 UTC, Peltorator commented
@yeputons, исправлено

2019-05-21 10:19 UTC, yeputons requested changes
* `04.sql`: ответ верный

2019-05-21 10:19 UTC, yeputons commented on task12/02.sql
> +    SELECT MAX(LiteracyRate.Year), LiteracyRate.CountryCode, LiteracyRate.Rate FROM LiteracyRate
Ну, в `SELECT` с группировкой может быть в общем случае два вида значений: либо то, по чему делали `GROUP BY` (потому что однозначно определяется для каждой группы), либо функция вроде `MAX()` (потому что она работает от всей группы). А `LiteracyRate.Rate` для группы определён неоднозначно => в общем случае непонятно, что тут будет.

2019-05-21 10:19 UTC, yeputons commented on task12/04.sql
> +LEFT JOIN City ON City.Population >= 1000000 AND City.CountryCode = Country.Code
Лучше сначала сравнить `CountryCode`, а потом уже население: сначала каноничный `JOIN`, а потом остальное

2019-05-21 10:22 UTC, Peltorator commented
@yeputons, исправлено

2019-05-21 10:27 UTC, yeputons requested changes
* `07.sql`: кажется, вы всё ещё считаете почти строго не то, что надо в задании.

2019-05-21 10:27 UTC, yeputons commented on task12/07.sql
> +HAVING (COUNT(City.Population) = 0 AND Country.Population > 0) OR 2 * SUM(City.Population) > Country.Population
Тут поможет `COALESCE`.

2019-05-21 10:41 UTC, Peltorator commented
@yeputons, исправлено

2019-05-21 12:14 UTC, yeputons requested changes
* `04.sql`: ответ верный, стиль есть
* `07.sql`: ответ верный, стиль есть

В `02.sql` пока ещё актуален старый вопрос

2019-05-21 12:36 UTC, Peltorator commented
Не уверен, что понимаю все, конечно, но что-то сделал...

2019-05-21 12:36 UTC, Peltorator commented
@yeputons, исправлено

2019-05-21 12:43 UTC, yeputons requested changes

2019-05-21 12:43 UTC, yeputons commented on task12/02.sql
> +    SELECT MAX(LiteracyRate.Year), CountryCode, Rate FROM LiteracyRate
Пока всё ещё такая же проблема: взяли таблицу `LiteracyRate`, сгруппировали по `CountryCode`, дальше для каждой группы вы просите вывести:

1. `MAX(LiteracyRate.Year)` - окей, это максимальный год в группе
2. `CountryCode` - окей, в группе это значение однозначно
3. `Rate` - непонятно, что выводить, потому что `Rate` в группе бывает разный. Упс. Не очень корректный SQL-запрос получается (впрочем, sqlite всё равно что-то делает).

2019-05-22 18:47 UTC, closed without merging