Task11, Group10, Им Евгений
yeputons/spring-2019-paradigms-tasks pull request #232
Opened 2019-05-18 18:52 UTC by evgenyim

2019-05-18 19:15 UTC, yeputons requested changes
Пока не хватает корректности: иногда неверно работает как минимум `delete`, не хватает тестов для `alter`, `lookup`, `size`

2019-05-18 19:15 UTC, yeputons commented on task11/src/Map.hs
> +            case c of
Это можно сделать при помощи функции `maybe` и без `case`

2019-05-18 19:15 UTC, yeputons commented on task11/src/Map.hs
> +             case c of
Для этого есть готовая функция

2019-05-18 19:15 UTC, yeputons commented on task11/src/Map.hs
> +              case c of
Это тоже можно переписать при помощи `maybe`

2019-05-18 19:15 UTC, yeputons commented on task11/src/Map.hs
> +        case Map.lookup k t of
Для этого есть готовая функция

2019-05-18 19:15 UTC, yeputons commented on task11/src/Map.hs
> +    notMember k t = not (member k t)
Тут лучше использовать композицию функций и убрать явный аргумент `t`

2019-05-18 19:15 UTC, yeputons commented on task11/src/Map.hs
> +    null t = (size t == 0)
Скобочки не нужны

2019-05-18 19:15 UTC, yeputons commented on task11/src/NaiveTree.hs
> +merge (Node k a l r) b = Node k a l (merge b r)
Выравнивайте аргументы друг под другом.
Не очень симметрично получается, что `a` и `b` обозначают совершенно разные вещи.

2019-05-18 19:15 UTC, yeputons commented on task11/src/NaiveTree.hs
> +    toAscList (Node k a l r) = toAscList l ++ ((k, a) : toAscList r)
Внешние скобочки справа не нужны

2019-05-18 19:15 UTC, yeputons commented on task11/src/NaiveTree.hs
> +    alter f k (Node k' a l r)
Лучше поменять `k` и `k'`, иначе получается, что у текущей вершины ключ `k'`, а значение без штриха

2019-05-18 19:15 UTC, yeputons commented on task11/src/NaiveTree.hs
> +    size (Node _ _ l r) = size l + size r + 1
Выравнивайте `=`

2019-05-18 21:07 UTC, evgenyim commented
@yeputons, исправлено

2019-05-19 12:48 UTC, edgarzhavoronkov requested changes
Здравствуйте, корректность вроде есть, остались небольшие замечания по стилю

2019-05-19 12:48 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    fromList = foldl (\x (k, a) -> insert k a x) empty
Можно задействовать `uncurry` и `flip`, что бы от параметров лямбды избавиться

2019-05-19 12:48 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    delete = alter (const Nothing)
`$` вместо скобок?

2019-05-19 12:48 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    adjust f = alter (fmap f)
Аналогично про `$`. А вообще приглядитесь, композиция же

2019-05-19 12:48 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    update f = alter (maybe Nothing f)
И тут доллар вместо скобок

2019-05-19 12:48 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    null t = size t == 0
Тут тоже можно композицию задействовать)

2019-05-19 12:48 UTC, edgarzhavoronkov commented on task11/src/NaiveTree.hs
> +      | otherwise = case f (Just a) of
Выглядит, как будто можно через `maybe` переписать

2019-05-19 15:17 UTC, evgenyim commented
@edgarzhavoronkov, исправлено

2019-05-20 16:28 UTC, yeputons requested changes

2019-05-20 16:28 UTC, yeputons commented on task11/src/Map.hs
> +    notMember k = not . (member k)
Скобочки не нужны

2019-05-20 16:28 UTC, yeputons commented on task11/src/Map.hs
> +    insertWith f k a = alter (Just . maybe a (f a)) k
Тут лучше `$` вместо внешних скобочек

2019-05-20 16:28 UTC, yeputons commented on task11/src/Map.hs
> +    null = (==0) . size
Поставьте пробел между `==` и `0`

2019-05-20 16:28 UTC, yeputons commented on task11/test/TestMap.hs
> +                let f key new old = (show key) ++ ":" ++ new ++ "|" ++ old in
Скобочки не нужны

2019-05-20 16:28 UTC, yeputons commented on task11/test/TestMap.hs
> +        testGroup "Test delete / adjust" [
Разнесите на две отдельные группы. Или они тут по какому-то принципу объединены?

2019-05-20 16:28 UTC, yeputons commented on task11/test/TestMap.hs
> +        testGroup "Test insert" [
Лучше просто `insert`, и так ясно, что тесты; аналогично ниже.
Не очень хорошо, что тут не упоминается `insertWith`/`insertWithKey`. Лучше тогда назвать `insert*`.

2019-05-20 16:28 UTC, yeputons commented on task11/test/TestMap.hs
> +            testCase "test insert in empty map" $
Уберите `test insert` в начале названия, это следует из группы, аналогично ниже

2019-05-20 16:28 UTC, yeputons commented on task11/test/TestMap.hs
> +        testGroup "Test alter/lookup/size" [
Разнесите на отдельные группы. Если в группе получается один тест — это не группа, а отдельный тест.

2019-05-21 17:01 UTC, evgenyim commented on task11/src/Map.hs
> +    insertWith f k a = alter (Just . maybe a (f a)) k
Там тогда компилятор на k ругается

2019-05-21 17:08 UTC, evgenyim commented
@yeputons, исправлено

2019-05-21 17:42 UTC, edgarzhavoronkov approved these changes
Как по мне, выглядит хорошо, думаю, что можно зачесть

2019-05-21 17:43 UTC, closed without merging