Task11, Group10, Салаватов Вадим
yeputons/spring-2019-paradigms-tasks pull request #233
Opened 2019-05-18 19:07 UTC by RemmargorP

@yeputons @edgarzhavoronkov

2019-05-18 19:22 UTC, yeputons requested changes
Корректность есть (и зачёт тоже!)

2019-05-18 19:22 UTC, yeputons commented on task11/src/Map.hs
> +    insertWith f key value = alter (\x -> case x of
Тут можно вынести общий `Just` и остаток выразить при помощи функции `maybe`

2019-05-18 19:22 UTC, yeputons commented on task11/src/Map.hs
> +    adjust f = alter (\x -> case x of
Для этого `case` есть готовая функция

2019-05-18 19:22 UTC, yeputons commented on task11/src/Map.hs
> +    update f = alter (\x -> case x of
Это тоже можно выразить через `maybe`

2019-05-18 19:22 UTC, yeputons commented on task11/src/NaiveTree.hs
> +merge (Node keyL valueL leftL rightL) right = Node keyL valueL leftL (merge rightL right)
* Слишком много длинных имён для Haskell, сократите до одной-двух букы.
* Выравнивайте аргументы друг под другом.

2019-05-18 19:22 UTC, yeputons commented on task11/src/NaiveTree.hs
> +    toAscList (Node key value left right) = toAscList left ++ [(key, value)] ++ toAscList right
Выравнивайте `=` друг под другом, в остальных местах тоже

2019-05-18 19:22 UTC, yeputons commented on task11/src/NaiveTree.hs
> +        | key < rkey = merge (alter f key rleft) (Node rkey rval Nil rright)
Какой-то странный `merge` с вершиной, у которой нет одного из детей.

2019-05-18 19:22 UTC, yeputons commented on task11/test/TestMap.hs
> +                ( Map.size map     == 4 &&
Это всё лучше записать как

```
let map = ... in do
Map.size     map @?= 4
Map.lookup 1 map @?= Just 2
```

2019-05-18 19:22 UTC, yeputons commented on task11/test/TestMap.hs
> +            testCase "insert is capable to insert into an empty map" $
Упростите название теста: `insert` понятно из названия группы, так что достаточно `into an empty map`, аналогично в остальных тестах

2019-05-18 19:22 UTC, yeputons commented on task11/test/TestMap.hs
> +                let map' = Map.adjust (7 +) 3 map in
Нехорошо, что операция коммутативная: не проверяется порядок аргументов. Аналогично в остальных тестах.

2019-05-20 19:17 UTC, edgarzhavoronkov commented
Я закрою ваш реквест, если не возражаете, тем более, что вас зачет уже есть

2019-05-20 19:17 UTC, closed without merging