Task11, Group10, Шиманская Ольга
yeputons/spring-2019-paradigms-tasks pull request #234
Opened 2019-05-18 19:41 UTC by jeinygroove

2019-05-18 19:54 UTC, yeputons requested changes
До корректности не хватает тестов на `alter`

2019-05-18 19:54 UTC, yeputons commented on task11/src/Map.hs
> +    adjust = alter . fmap
Лайк

2019-05-18 19:54 UTC, yeputons commented on task11/test/TestMap.hs
> +                (Map.size map     == 2            &&
Тут лучше написать
```
let map = ... in do
Map.size map @?= 2
Map.lookup 1 map @?= Just "hello"
```
Аналогично в остальных местах

2019-05-18 22:10 UTC, jeinygroove commented
@yeputons исправлено

2019-05-19 12:53 UTC, edgarzhavoronkov requested changes
Добрый день, пара замечаний

2019-05-19 12:53 UTC, edgarzhavoronkov commented on task11/test/TestMap.hs
> +        testGroup "Unite test for insert" [
typo: Unit здесь и далее

2019-05-19 12:53 UTC, edgarzhavoronkov commented on task11/test/TestMap.hs
> +            testCase "adjust doesn't change a map an empty map" $
Группа тестов для `alter` а тесты для `adjust`?

2019-05-19 13:15 UTC, jeinygroove commented
@edgarzhavoronkov исправлено

2019-05-19 13:46 UTC, edgarzhavoronkov approved these changes
Вроде все хорошо, зачтено

2019-05-19 21:12 UTC, closed without merging