Task11, Group10, Эмдин Григорий
yeputons/spring-2019-paradigms-tasks pull request #235
Opened 2019-05-18 19:55 UTC by egdegd

2019-05-18 20:17 UTC, edgarzhavoronkov requested changes
Здравствуйте, автотесты проходят, но некоторое количество ремарок есть

2019-05-18 20:17 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    fromList = foldl (\x (k, a) -> insert k a x) empty
Тут можно использовать либо правую свертку, либо `uncurry` и `flip` и избавиться от параметров лямбды

2019-05-18 20:17 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    delete = alter (const Nothing)
`$` вместо скобок лучше

2019-05-18 20:17 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    member k t =
Кажется можно проще выразить) Есть функция `isJust`

2019-05-18 20:17 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    notMember k t = not (member k t)
Композиция тут будет уместнее смотреться

2019-05-18 20:17 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    null t = (size t == 0)
Внешние скобки не нужны

2019-05-18 20:17 UTC, edgarzhavoronkov commented on task11/src/NaiveTree.hs
> +    toAscList (Node k a l r) = toAscList l ++ ((k, a) : toAscList r)
Вроде внешние скобки вокруг правого списка не нужны

2019-05-18 20:17 UTC, edgarzhavoronkov commented on task11/src/NaiveTree.hs
> +      | otherwise = case f (Just a) of
Нельзя это через `maybe` выразить?

2019-05-18 20:17 UTC, edgarzhavoronkov commented on task11/test/TestMap.hs
> +            testCase "test insert in empty map" $
Можно наверное переимновать тест, так как есть группа, в названии которой написано, что она вставку тестирует

2019-05-18 20:17 UTC, edgarzhavoronkov commented on task11/test/TestMap.hs
> +            testCase "test insert in empty map" $
Далее аналогично

2019-05-18 20:17 UTC, edgarzhavoronkov commented on task11/test/TestMap.hs
> +            testCase "test insert in not empty map" $
`non-empty`

2019-05-18 20:21 UTC, edgarzhavoronkov commented
Добавлю, что проглядел тесты на `alter`. Они тоже нужны

2019-05-18 20:44 UTC, egdegd commented
@edgarzhavoronkov, исправлено

2019-05-18 21:00 UTC, egdegd commented
я тест добавил, этого для корректности достаточно?

2019-05-18 21:01 UTC, edgarzhavoronkov commented
Ага, вернул балл

2019-05-19 12:54 UTC, edgarzhavoronkov requested changes
Напишу, что стилевые замечания актуальны, что бы бот убрал отметку

2019-05-20 19:13 UTC, closed without merging