Task11, Group10, Черногорский Федор
yeputons/spring-2019-paradigms-tasks pull request #236
Opened 2019-05-18 20:28 UTC by CHern0g0r

2019-05-18 20:54 UTC, edgarzhavoronkov requested changes
Здравствуйте, автотесты проходят, но есть энное количество ремарок

2019-05-18 20:54 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    insertWith f k a = alter (\x -> case x of
Посмотрите в сторону `maybe`, она ровно этим и занимается

2019-05-18 20:54 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    delete = alter (const Nothing)
Что бы не писать скобкочки можно `$` использовать

2019-05-18 20:54 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    notMember k t = not (member k t)
А здесь композицию впилить

2019-05-18 20:54 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    null = (== 0) . size
Лайк

2019-05-18 20:54 UTC, edgarzhavoronkov commented on task11/src/NaiveTree.hs
> +    toAscList (Node k a l r) = toAscList l ++ [(k, a)] ++ toAscList r
Лучше пару `(k, a)` приделывать в голову списка с помощью констурктора, хотя у вас эстетически приятнее выглядит

2019-05-18 20:54 UTC, edgarzhavoronkov commented on task11/src/NaiveTree.hs
> +                a' = maybe Nil (singleton k) (f (Just a)) in
Подвиньте еще на уровень вправо

2019-05-18 20:54 UTC, edgarzhavoronkov commented on task11/test/TestMap.hs
> +        testGroup "Test empty, singleton" [
Назовите, пожалуйста, группы тестов единообразно и тесты в них тоже соответствующим образом. У отдельно взятого теста можно не писать какую функцию он тестирует, это из названия группы должно быть ясно

2019-05-20 10:02 UTC, CHern0g0r commented
@edgarzhavoronkov, исправлено

2019-05-20 16:16 UTC, yeputons requested changes
* `cabal new-build task11` падает с ошибкой: не компилируется

2019-05-21 21:34 UTC, CHern0g0r commented
@yeputons-bot, исправлено

2019-05-21 23:26 UTC, edgarzhavoronkov requested changes
Два небольших замечания. Корректность есть в целом

2019-05-21 23:26 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    fromList = foldl (\m (k, a) -> insert k a m) empty
Поглядите в сторону `uncurry` и `flip` с их помощью можно от лямбды избавиться

2019-05-21 23:26 UTC, edgarzhavoronkov commented on task11/src/NaiveTree.hs
> +                a' = maybe Nil (singleton k) (f (Just a)) in
или хотя бы `in` перенесите на строку вниз

2019-05-21 23:38 UTC, CHern0g0r commented
@yeputons-bot, исправлено

2019-05-21 23:55 UTC, edgarzhavoronkov requested changes
Дожмем

2019-05-21 23:55 UTC, edgarzhavoronkov commented on task11/src/NaiveTree.hs
> +                in merge l (merge a' r)
Еще вправо, иначе неясно, к чему он относится

2019-05-22 08:35 UTC, CHern0g0r commented
@yeputons-bot, исправлено

2019-05-22 10:51 UTC, edgarzhavoronkov approved these changes
LGTM

2019-05-22 10:51 UTC, closed without merging