Task12, Group10, Черногорский Федор
yeputons/spring-2019-paradigms-tasks pull request #238
Opened 2019-05-19 09:23 UTC by CHern0g0r

2019-05-19 13:36 UTC, edgarzhavoronkov requested changes
Здравствуйте!

* `01.sql`: ответ верный
* `02.sql`: ответ верный
* `03.sql`: ответ верный
* `04.sql`: ответ верный
* `05.sql`: ответ верный
* `06.sql`: ответ верный
* `07.sql`: не сошлось число строк: ожидалось 208, получено 25
* `08.sql`: не сошлось число столбцов: ожидалось 3, получено 2

2019-05-19 13:36 UTC, edgarzhavoronkov commented on task12/01.sql
> +SELECT Name FROM Country ORDER BY SurfaceArea DESC, Name DESC LIMIT 5;
Внезапно, Name DESC это точно лексикографический порядок?

2019-05-19 13:36 UTC, edgarzhavoronkov commented on task12/04.sql
> +GROUP BY Country.Name
Лучше наверное по коду группировать, в названии страны опечататься легко

2019-05-19 13:36 UTC, edgarzhavoronkov commented on task12/07.sql
> +HAVING SUM(City.Population) > (Country.Population - SUM(City.Population))
Поглядите в сторону COALESCE

2019-05-19 13:36 UTC, edgarzhavoronkov commented on task12/08.sql
> +SELECT Country.Name, City.Population
Кажется площадь страны забыли

2019-05-19 13:38 UTC, edgarzhavoronkov commented on task12/04.sql
> +GROUP BY Country.Name
Плюс взгляните в сторону SUM(CASE ... )

2019-05-19 13:40 UTC, edgarzhavoronkov commented on task12/06.sql
> +ORDER BY CAST (City.Population AS FLOAT) / CAST (Country.Population AS FLOAT) DESC, City.Name DESC
тут что бы не кастить можно на 1.0 умножить, я думаю

2019-05-21 22:40 UTC, CHern0g0r commented
@yeputons-bot, исправлено

2019-05-21 23:17 UTC, edgarzhavoronkov requested changes
Здравствуйте, 

Вроде ок, кроме восьмого, говорит неверный ответ

2019-05-22 12:49 UTC, closed without merging