Task09, Group10, Черногорский Федор
yeputons/spring-2019-paradigms-tasks pull request #245
Opened 2019-05-20 10:50 UTC by CHern0g0r

@edgarzhavoronkov, исправлено

2019-05-20 16:09 UTC, yeputons requested changes
Идея верная, но корректности пока нет: есть ошибки на Travis (не совсем корректный стиль кода, присутствуют предупреждения-ошибки при компиляции)

2019-05-21 22:01 UTC, CHern0g0r commented
@yeputons-bot, исправлено

2019-05-21 22:41 UTC, CHern0g0r commented
@yeputons-bot, исправлено

2019-05-21 23:53 UTC, edgarzhavoronkov requested changes
Здравствуйте, корректность вроде есть, некоторые вопросы по коду остались

2019-05-21 23:53 UTC, edgarzhavoronkov commented on task09/src/tsqueue_test.cpp
> +            int number = 73;
`ping`

2019-05-21 23:53 UTC, edgarzhavoronkov commented on task09/src/tsqueue_test.cpp
> +            int *result =
`pong` =)

2019-05-21 23:53 UTC, edgarzhavoronkov commented on task09/src/tsqueue.h
> +    pthread_cond_t cond;
Непонятное название, `non_empty` думаю лучше будет

2019-05-21 23:53 UTC, edgarzhavoronkov commented on task09/src/tsqueue.cpp
> +    pthread_mutex_lock(&q->mutex);
А зачем здесь захват и освобождение блокировки?

2019-05-21 23:53 UTC, edgarzhavoronkov commented on task09/src/tsqueue.cpp
> +    pthread_mutex_destroy(&q->mutex);
Ресурсы лучше высвобождать в порядке обратном созданию

2019-05-21 23:53 UTC, edgarzhavoronkov commented on task09/src/tsqueue.cpp
> +    pthread_mutex_lock(&q->mutex);
И в деструкторе тот же вопрос

2019-05-22 09:42 UTC, CHern0g0r commented
@yeputons-bot, исправлено

2019-05-22 10:55 UTC, edgarzhavoronkov approved these changes
Вроде окей, зачел

2019-05-22 10:55 UTC, closed without merging