Task06-1, Group09, Быков Никита
yeputons/spring-2019-paradigms-tasks pull request #265
Opened 2019-05-21 16:15 UTC by StillBlueSkyOverhead

@yeputons

2019-05-21 18:27 UTC, yeputons requested changes
По заданию требуется, чтобы исходные `model.py` и `test_model.py` из `task04` создавались отдельным коммитом. Сейчас они у вас уже зачтены — возьмите, пожалуйста, в точности зачтённую версию.

2019-05-21 19:40 UTC, StillBlueSkyOverhead commented
@yeputons, исправлено

2019-05-21 20:01 UTC, StillBlueSkyOverhead commented
@yeputons, исправлено

2019-05-21 20:31 UTC, StillBlueSkyOverhead commented
@yeputons, исправлено

2019-05-22 10:18 UTC, yeputons requested changes
* По первой задаче остался стиль: `print_` вместо `_print` (чтобы не было путаницы с "приватными" полями)
* constant_folder
	* Не проходит автотесты: иногда падает сворачивание бинарных выражений, иногда в бинарных выражениях сворачивается слишком много. Подсказка: вашими тестами их вы в текущем виде принципиально не поймате (могу дать ещё подсказку), хотя тесты на это есть. А вот если запускать напрямую, то поймаете.

2019-05-22 10:18 UTC, yeputons commented on task06/model.py
> +    def visit_print(self, _print):
Лучше `print_`

2019-05-22 10:19 UTC, yeputons commented
P.S. В коммите e1c65196c69f20b036b95ec0a3bc5c9b182f5c9c лежат корректные версии, не меняйте его, пожалуйста

2019-05-22 11:58 UTC, StillBlueSkyOverhead commented
@yeputons, исправлено

2019-05-22 12:07 UTC, StillBlueSkyOverhead commented
@yeputons, исправлено

2019-05-22 12:26 UTC, yeputons requested changes
Корректность есть, тема есть, зачёт есть, поздравляю!

2019-05-22 12:26 UTC, yeputons commented on task06/folder.py
> +        if isinstance(lhs, Number) and lhs == Number(0) and \
Лучше `()` вместо `\`

2019-05-22 12:26 UTC, yeputons commented on task06/folder.py
> +                isinstance(rhs, number) and rhs == Number(0):
Конечно, тут в идеале бы эту проверку `isinstance` сделать внутри `__eq__` у `Number` и возвращать `NotImplemented`, если не получилось (не исключение выдавать, а именно возвращать, чтобы Python мог в другую сторону аргументы попробовать)

2019-05-22 18:47 UTC, closed without merging