Task11, Group10, Старков Борис
yeputons/spring-2019-paradigms-tasks pull request #271
Opened 2019-05-21 19:42 UTC by PennyroyalTea

2019-05-21 20:18 UTC, edgarzhavoronkov requested changes
Добрый день,

Автотесты проходят, корректность вроде есть, по стилю немного замечаний

2019-05-21 20:18 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    insertWith f key value  = alter (maybe (Just value) (Just . f value)) key
Кажется, что можно вынести `Just` из обоих веток

2019-05-21 20:18 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +
Непонятно зачем добавленная пустая строка

2019-05-21 20:18 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    delete = alter (const Nothing)
В хаскеле больше принято `$` использовать вместо таких скобок

2019-05-21 20:18 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    delete = alter (const Nothing)
Аналогично и далее

2019-05-21 20:18 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    adjust f = alter (maybe Nothing (Just . f))
Тоже самое можно сделать с помощью `fmap` -- Maybe это же функтор

2019-05-21 20:18 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    notMember key = not . member key
Параметр можно убрать

2019-05-21 20:18 UTC, edgarzhavoronkov commented on task11/src/NaiveTree.hs
> +    toAscList (Node key value left right) = toAscList left ++ [(key, value)] ++ toAscList right
Поменяйте местами эту и следующую строки. У вас случай пустого дерева везде первым разбирается, а здесь нет

2019-05-21 20:40 UTC, PennyroyalTea commented on task11/src/Map.hs
> +    insertWith f key value  = alter (maybe (Just value) (Just . f value)) key
Нельзя, он на типы ругается :( Фукнция должна быть Maybe a -> Maybe a

2019-05-21 20:47 UTC, PennyroyalTea commented on task11/src/Map.hs
> +    notMember key = not . member key
Если убрать, по типам не сходится. Я ведь к mp последовательно применяю member key, not , а не применяю not member сначала к key потом к mp

2019-05-21 20:49 UTC, PennyroyalTea commented on task11/src/Map.hs
> +    adjust f = alter (maybe Nothing (Just . f))
не смог понять

2019-05-21 20:51 UTC, PennyroyalTea commented
@edgarzhavoronkov исправил что-то

2019-05-21 20:51 UTC, PennyroyalTea commented
@edgarzhavoronkov исправлено

2019-05-21 21:30 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    adjust f = alter (maybe Nothing (Just . f))
У вас есть функция `maybe` которая берет значение типа `Maybe a`, функцию `a -> b` и некоторое значение по умолчанию типа `b`. Если ей дали `Just x`, то она применяет функцию к иксу и возвращает получившееся в результате значение. Если же ей дали `Nothing`, то она возвращает данное ей значение по умолчанию

Приглядитесь, что вы скармливайте `maybe`. Если у вас внутри ничего не лежит, то вы возвращаете `Nothing`, если что-то лежит, то вы применяете `f`, а затем запаковывайте обратно в `Just`. 

Оператор на типами `Maybe` является функтором. Это значит, что значения этого типа можно отобразить с сохранением структуры(`Just` в `Just`, `Nothing` в `Nothing`), звучит похоже не правда ли?

2019-05-21 21:31 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    notMember key = not . member key
Да, я дурак, извините(

2019-05-21 21:33 UTC, edgarzhavoronkov requested changes
Стало лучше, три замечания вроде бы по стилю остались

2019-05-21 21:33 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    insertWith f key value  = alter (maybe (Just value) (Just . f value)) key
Можно, поверьте

2019-05-21 21:33 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    update f = alter $maybe Nothing f
Пробел после бакса

2019-05-21 21:50 UTC, PennyroyalTea commented on task11/src/Map.hs
> +    insertWith f key value  = alter (maybe (Just value) (Just . f value)) key
Под "вынести" имеется в виду убрать?

2019-05-21 21:56 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    insertWith f key value  = alter (maybe (Just value) (Just . f value)) key
Нет, за скобки попробуйте вынести)

2019-05-21 21:56 UTC, PennyroyalTea commented on task11/src/Map.hs
> +    insertWith f key value  = alter (maybe (Just value) (Just . f value)) key
Если я просто убираю, то падает.
Expected type: Maybe a -> Maybe a
        Actual type: Maybe a -> a

2019-05-21 21:59 UTC, PennyroyalTea commented
@edgarzhavoronkov исправлено

2019-05-21 22:04 UTC, PennyroyalTea commented
@edgarzhavoronkov исправлено

2019-05-21 22:27 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    insertWith f key value  = alter (maybe (Just value) (Just . f value)) key
А теперь посмотрите, какой тип имеет `maybe value (f value)` и что нужно сделать, что бы получилась функция `Maybe a -> Maybe a`

2019-05-21 22:30 UTC, PennyroyalTea commented on task11/src/Map.hs
> +    insertWith f key value  = alter (maybe (Just value) (Just . f value)) key
Тут как-то сообщения долго доходят, я починил уже!

2019-05-21 23:07 UTC, edgarzhavoronkov requested changes
Очень хорошо, осталось пара мелких замечаний

2019-05-21 23:07 UTC, edgarzhavoronkov commented on task11/src/NaiveTree.hs
> +    toAscList (Node key value left right) = toAscList left ++ [(key, value)] ++ toAscList right
Тут можно пару `(key, value)` сразу в голову правому списку писать с помощью конструктора

2019-05-21 23:07 UTC, edgarzhavoronkov commented on task11/src/Map.hs
> +    adjust f = alter $ fmap f
Можно до композиции добить

2019-05-22 05:49 UTC, PennyroyalTea commented
@edgarzhavoronkov исправлено

2019-05-22 05:49 UTC, PennyroyalTea commented on task11/src/Map.hs
> +    adjust f = alter $ fmap f
не понимаю сходу, как

2019-05-22 09:37 UTC, edgarzhavoronkov approved these changes
LGTM, стиль появился

2019-05-22 09:38 UTC, closed without merging