Task12, Group10, Старков Борис
yeputons/spring-2019-paradigms-tasks pull request #272
Opened 2019-05-21 20:07 UTC by PennyroyalTea

Я пока в процессе выполнения, не надо проверять

2019-05-21 20:19 UTC, PennyroyalTea commented
Хотя ладно, че уж, можно проверять 🌝

2019-05-21 20:21 UTC, edgarzhavoronkov approved these changes
Да нормально, можете еще досылать, если хотите, я могу пока не закрывать реквест)
Кажется, что если сдадите восьмое задание и здесь(и в task11 за стиль) добъете баллов, то зачет будет

2019-05-21 22:22 UTC, edgarzhavoronkov requested changes
Корректность есть у 3 и 5, стиль еще и у 3

2019-05-21 22:22 UTC, edgarzhavoronkov commented on task12/05.sql
> +SELECT GovernmentForm, SUM(SurfaceArea)
Можно как-нибудь обозвать эту сумму, что бы дважды не писать

2019-05-21 22:40 UTC, PennyroyalTea commented
@edgarzhavoronkov исправлено

2019-05-21 23:13 UTC, edgarzhavoronkov requested changes
5 -- добавился стиль
6 -- окей
8 -- можно обойтись без подзапроса?

2019-05-21 23:13 UTC, edgarzhavoronkov commented on task12/08.sql
> +SELECT Country.Name, City.Population, Country.SurfaceArea
`City.Population`?

2019-05-22 09:52 UTC, edgarzhavoronkov approved these changes
2, 4 -- окей

2019-05-22 09:52 UTC, closed without merging