Task12, Group09, Козловцева Мария
yeputons/spring-2019-paradigms-tasks pull request #295
Opened 2019-05-30 16:30 UTC by MashaK5

2019-05-30 16:31 UTC, MashaK5 commented
@yeputons

2019-05-31 05:38 UTC, yeputons requested changes
* `01.sql`: ответ верный, стиль есть
* `03.sql`: ответ верный, стиль есть
* `04.sql`: не сошлось число строк: ожидалось 239, получено 77
* `05.sql`: ответ верный, стиль почти
* `06.sql`: ответ верный, стиль есть
* `07.sql`: не сошлось число строк: ожидалось 208, получено 207

2019-05-31 05:38 UTC, yeputons commented on task12/05.sql
> +ORDER BY SUM(SurfaceArea) DESC
Лучше в `SELECT` дать имя этому столбцу (`SELECT выражение1, выражение2 AS XyZ`), а тут отсортировать по `XyZ`. Ну и не `XyZ`, конечно, а более содержательное имя.

2019-05-31 05:57 UTC, MashaK5 commented
@yeputons, исправлено

2019-05-31 06:42 UTC, MashaK5 commented
@yeputons, исправлено

2019-05-31 11:36 UTC, yeputons approved these changes
Корректность и стиль в 01, 03, 04, 05, 06, 07 есть, тема зачтена, на один шаг ближе к зачёту (как договаривались в письме)

2019-05-31 11:36 UTC, yeputons commented on task12/05.sql
> +SELECT GovernmentForm, SUM(SurfaceArea) AS SumSA FROM Country
nit: лучше `TotalSurfaceArea`

2019-05-31 11:36 UTC, closed without merging